"""initial_component_schema

Revision ID: 1a8e8c6614a7
Revises: 
Create Date: 2026-04-28 00:56:44.938733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8e8c6614a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('merchant_id', sa.String(length=255), nullable=False))
    op.add_column('components', sa.Column('component_type', sa.String(length=50), nullable=False))
    op.add_column('components', sa.Column('on_hand', sa.Float(), nullable=False))
    op.add_column('components', sa.Column('reserved', sa.Float(), nullable=False))
    op.add_column('components', sa.Column('available', sa.Float(), nullable=False))
    op.add_column('components', sa.Column('threshold', sa.Float(), nullable=False))
    op.add_column('components', sa.Column('reorder_qty', sa.Float(), nullable=True))
    op.add_column('components', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('components', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('components', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.drop_index('ix_components_sku', table_name='components')
    op.create_index(op.f('ix_components_sku'), 'components', ['sku'], unique=False)
    op.create_index(op.f('ix_components_is_active'), 'components', ['is_active'], unique=False)
    op.create_index(op.f('ix_components_merchant_id'), 'components', ['merchant_id'], unique=False)
    op.drop_column('components', 'reorder_level')
    op.drop_column('components', 'current_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('current_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('components', sa.Column('reorder_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_components_merchant_id'), table_name='components')
    op.drop_index(op.f('ix_components_is_active'), table_name='components')
    op.drop_index(op.f('ix_components_sku'), table_name='components')
    op.create_index('ix_components_sku', 'components', ['sku'], unique=True)
    op.drop_column('components', 'notes')
    op.drop_column('components', 'lead_time_days')
    op.drop_column('components', 'supplier')
    op.drop_column('components', 'reorder_qty')
    op.drop_column('components', 'threshold')
    op.drop_column('components', 'available')
    op.drop_column('components', 'reserved')
    op.drop_column('components', 'on_hand')
    op.drop_column('components', 'component_type')
    op.drop_column('components', 'merchant_id')
    # ### end Alembic commands ###
