"""add cost_per_unit to components

Revision ID: 5bf1cd1a7283
Revises: b6f4e1c3db68
Create Date: 2026-05-10 19:05:49.462498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf1cd1a7283'
down_revision: Union[str, None] = 'b6f4e1c3db68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('cost_per_unit', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'cost_per_unit')
    # ### end Alembic commands ###
