"""add_bom_models

Revision ID: 70e7e45ff1e9
Revises: 1a8e8c6614a7
Create Date: 2026-04-28 23:43:32.142188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e7e45ff1e9'
down_revision: Union[str, None] = '1a8e8c6614a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('shopify_variant_id', sa.String(), nullable=False),
    sa.Column('shopify_product_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_variants_id'), 'shopify_variants', ['id'], unique=False)
    op.create_index(op.f('ix_shopify_variants_merchant_id'), 'shopify_variants', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_shopify_variants_shopify_variant_id'), 'shopify_variants', ['shopify_variant_id'], unique=True)
    op.create_table('boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['shopify_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    op.create_index(op.f('ix_boms_id'), 'boms', ['id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Float(), nullable=False),
    sa.Column('waste_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'component_id', name='uq_bom_component')
    )
    op.create_index(op.f('ix_bom_lines_id'), 'bom_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_lines_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_boms_id'), table_name='boms')
    op.drop_table('boms')
    op.drop_index(op.f('ix_shopify_variants_shopify_variant_id'), table_name='shopify_variants')
    op.drop_index(op.f('ix_shopify_variants_merchant_id'), table_name='shopify_variants')
    op.drop_index(op.f('ix_shopify_variants_id'), table_name='shopify_variants')
    op.drop_table('shopify_variants')
    # ### end Alembic commands ###
